name: USDT=Dollar Auto Poster (every 5 min)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/5 * * * *"   # каждые 5 минут (UTC)

concurrency:
  group: autopost
  cancel-in-progress: true  # не пускать два прогона одновременно

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run poster
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          TIMEZONE: Europe/Zurich
          # Ниже можно тонко подстроить «свежесть» и частоту
          MAX_POSTS_PER_RUN: "6"      # сколько новостей за один прогон
          LOOKBACK_MINUTES: "30"      # доп. окно на случай лагов фидов
          FRESH_WINDOW_MIN: "20"      # считаем «самыми свежими» (минут)
          MIN_EVENT_YEAR: "2023"      # отсечь старые вечнозелёные
        run: |
          python bot/poster.py
