name: Auto Poster (every 10 min)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # каждые 10 минут (UTC) → :00, :10, :20 ...

permissions:
  contents: write   # нужно для коммита data/history.json

concurrency:
  group: autopost
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run poster
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}   # например @usdtdollarm
          TIMEZONE: Europe/Moscow
          MAX_POSTS_PER_RUN: "1"         # ровно 1 новость за прогон
          LOOKBACK_MINUTES: "30"
          FRESH_WINDOW_MIN: "25"
          MIN_EVENT_YEAR: "2023"
        run: |
          python bot/poster.py

      - name: Persist state (data/)
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/state.json data/history.json || true
          git commit -m "bot: update state $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push || echo "no push"
