name: Auto Poster (every 12 min)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/12 * * * *"   # каждые 12 минут (UTC)

concurrency:
  group: autopost
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run poster
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          TIMEZONE: Europe/Moscow
          MAX_POSTS_PER_RUN: "1"       # 1 пост за прогон → ~5/час
          LOOKBACK_MINUTES: "30"
          FRESH_WINDOW_MIN: "25"
          MIN_EVENT_YEAR: "2023"
        run: |
          python bot/poster.py
