name: USDT=Dollar Auto Poster (cron)

on:
  schedule:
    - cron: "*/5 * * * *"  # каждые 5 минут (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run poster
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          TIMEZONE: ${{ vars.TIMEZONE }}
        run: |
          python bot/poster.py

      - name: Commit state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/state.json || true
          git commit -m "update state" || echo "no changes"
          git push || true
